// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCflabBeIT4v1qUkJWms3VoNrge6phbciQ",
      authDomain: "taxi-booking-810bf.firebaseapp.com",
      projectId: "taxi-booking-810bf",
      storageBucket: "taxi-booking-810bf.appspot.com",
      messagingSenderId: "522987428134",
      appId: "1:522987428134:web:f0becd202c8b7139e809e7",
      measurementId: "G-Z8X6437N06");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcQyEDsS5IErctJaZ14OtgBInWSMkoTN8',
    appId: '1:198770247800:android:3d6b43074f39398f8c458d',
    messagingSenderId: '198770247800',
    projectId: 'ubar-jko',
    storageBucket: 'ubar-jko.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyCflabBeIT4v1qUkJWms3VoNrge6phbciQ",
    authDomain: "taxi-booking-810bf.firebaseapp.com",
    projectId: "taxi-booking-810bf",
    storageBucket: "taxi-booking-810bf.appspot.com",
    messagingSenderId: "522987428134",
    appId: "app-1-522987428134-ios-6bf7481de39f97c5e809e7",
    measurementId: "G-Z8X6437N06",
    androidClientId: '522987428134-aq4d1ei9571vouqqovja59uj5hqi9bho.apps.googleusercontent.com',
    iosClientId: '522987428134-f8lkt3rai45nnpf2nhs90c51unt81mm7.apps.googleusercontent.com',
    iosBundleId: 'com.mighty.taxirider2',
  );

}
